version: '3'
services:
  postgresql:
    image: postgres:13-alpine
    container_name: postgresql
    restart: always
    # volumes:
    #   - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'rssuser'
      POSTGRES_PASSWORD: 'rssuser'
      POSTGRES_DB: 'logdb'
      TZ: 'Asia/Seoul'
