server:
  port: 8081
  servlet:
    contextPath: /servicemanager
servicemanager:
  type: "OTS"
  diskUsageDirectory: /CANON/LOG
  espContainerNameList: Database, Rapid-Collector
  otsContainerNameList: FileServiceCollect
